geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core.views import *
from product.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', VegetablesListView.as_view(), name='homepage'),
    path('categories/', CategoryListView.as_view(), name="categories"),
    path('category/<int:id>/', CategoryDetailView.as_view(), name="category"),
    path('about/', AboutView.as_view()),
    path('price/', price_view),
    path('vegetables/<pk>/', VegetableDetailView.as_view()),
    path('vegetables/update/<id>/', vegetable_update, name='vegetable-update'),
    path('vegetables/delete/<id>/', vegetable_delete, name='vegetable-delete'),
    path('vegetable_add/', vegetable_add, name='vegetable_add'),
    path('feedback', feedback_view, name="feedback"),
    path('feedback_form/', feedback_form_view, name="feedback_form"),
    path('signin/', sign_in, name='sign-in'),
    path('signout/', logout_from_site, name='sign-out')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models


class Feedback(models.Model):
    first_name = models.CharField(max_length=255)
    rating = models.IntegerField(default=10)
    text = models.TextField(null=True, blank=True)
    contact = models.CharField(max_length=255, verbose_name='Номер или email для связи')

product/models.py
from django.db import models



class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"


# Create your models here.
class Vegetables(models.Model):
    name = models.CharField(max_length=255)
    calories = models.IntegerField(default=0)
    price = models.PositiveIntegerField(default=1)
    is_avialable = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        to=Category, null=True, blank=True, related_name='vegetables',
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return f"{self.id} - {self.name}"

core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Feedback


class FeedbackCreateForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = "__all__"


class SignInForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Feedback
from .forms import FeedbackCreateForm, SignInForm


# Create your views here.
def price_view(request):
    return render(request, "core/price.html")


def feedback_view(request):
    # ...
    if request.method == "POST":
        data = request.POST
        feedback = Feedback()
        feedback.first_name = data["first_name"]
        feedback.rating = int(data["rating"])
        feedback.text = data["text"]
        feedback.contact = data["contact"]
        feedback.save()
        return HttpResponse("Ваш отзыв принят! Спасибо!")


    return render(request, "core/feedback.html")


@login_required(login_url='http://localhost:8000/signin/')
def feedback_form_view(request):
    context = {}

    if request.method == "POST":
        feedback_create_form = FeedbackCreateForm(request.POST)
        feedback_create_form.save()
        return HttpResponse("Ваш отзыв принят! Спасибо!")

    feedback_create_form = FeedbackCreateForm()
    context["feedback_create_form"] = feedback_create_form
    return render(request, "core/feedback_form.html", context)


def sign_in(request):
    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"]
        )

        if user is not None:
            login(request, user)
            return redirect('homepage')
    context = {"auth_form": SignInForm()}
    return render(request, 'core/sign_in.html', context)


@login_required()
def logout_from_site(request):
    logout(request)
    return redirect('homepage')

product/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import ListView, DetailView
from .models import Vegetables, Category
from .forrms import VegetableCreateForm
from core.decorators import should_be_staff


class AboutView(TemplateView):
    template_name = "about.html"


def about(request):
    return render(request, 'about.html')


# Create your views here.
# model, template
# def homepage(request):
#     # SELECT * FROM Vegetables
#     products = Vegetables.objects.all()  # list
#     context = {"all_vegetables": products}
#     return render(request, "product/list.html", context)


class VegetablesListView(ListView):
    model = Vegetables
    template_name = "product/list.html"
    # queryset = Vegetables.objects.filter(is_avialable=True)

    def get_queryset(self):
        return Vegetables.objects.filter(is_avialable=True)

# def categories_view(request):
#     categories = Category.objects.all()
#     c = {"categories": categories}
#     return render(request, "product/categories.html", c)


class CategoryListView(ListView):
    model = Category
    template_name = "product/catigorie.html"


# def vegetable_detail(request, id):
#     try:
#         vegetable = Vegetables.objects.get(id=id)
#         context = {"vegetable": vegetable}
#         return render(request, "product/vegetable_info.html", context)
#     except Vegetables.DoesNotExist:
#         return HttpResponse("Такой страницы не существует", status=404)


class VegetableDetailView(DetailView):
    model = Vegetables
    template_name = "product/vegetable_info.html"


# def category_detail(request, id):
#     # SELECT * FROM Vegetables WHERE category = (SELECT id FROM Category WHERE id = id)
#     category_object = Category.objects.get(id=id)
#     vegetables_list = Vegetables.objects.filter(category=category_object)
#     context = {"all_vegetables": vegetables_list}
#     return render(request, "product/list.html", context)


class CategoryDetailView(DetailView):
    model = Category
    template_name = "product/list.html"

    def get(self, request, *args, **kwargs):
        return HttpResponse("hello")

    def get_object(self):
        return Category.objects.get(id=self.kwargs["id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Vegetables.objects.filter(category=self.object)
        return context


@login_required(login_url='http://localhost:8000/signin/')
# @permission_required("product.add_vegetable")
@should_be_staff
def vegetable_add(request):
    # if not request.user.is_staff:
    #     return HttpResponse("У вас нет доступа!", status=403)

    context = {}

    if request.method == "GET":
        vegetable_form = VegetableCreateForm()
        context["vegetable_form"] = vegetable_form
        return render(request, 'product/vegetable_form.html', context)

    elif request.method == "POST":
        vegetable_form = VegetableCreateForm(request.POST)
        if vegetable_form.is_valid():
            new_vegetable = vegetable_form.save()
            return redirect(vegetable_add, id=new_vegetable.id)
        else:
            return HttpResponse("Форма не валидна", status=400)


def vegetable_update(request, id):
    context = {}
    vegetable_object = Vegetables.objects.get(id=id)

    if request.method == "POST":
        vegetable_form = VegetableCreateForm(request.POST, instance=vegetable_object)
        if vegetable_form.is_valid():
            vegetable_object = vegetable_form.save()
            return HttpResponse("Данные сохранены")

    vegetable_form = VegetableCreateForm(instance=vegetable_object)
    context["vegetable_form"] = vegetable_form
    return render(request, 'product/vegetable_form.html', context)


def vegetable_delete(request, id):
    if request.method == "POST":
        vegetable_object = Vegetables.objects.get(id=id)
        vegetable_object.delete()
        return HttpResponse("Информация успешно удалена!")

core/templates/core/about.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Hi</h1>
</body>
</html>

core/templates/core/feedback.html
{% extends 'base.html' %}
{% block content %}

  <form method="POST">
    {% csrf_token %}
    <input name="first_name" type="text" placeholder="Имя"><br/><br/>
    <input name="rating" type="number" placeholder="Оценка"><br/><br/>
    <textarea name="text" id="" cols="30" rows="3"></textarea><br/><br/>
    <input name="contact" type="text" placeholder="Контакт"><br/><br/>
    <button>Отправить</button>
  </form>

{% endblock %}

core/templates/core/feedback_form.html
{% extends 'base.html' %}
{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{ feedback_create_form.as_p }}
    <button>Отправить</button>
  </form>

{% endblock %}

core/templates/core/price.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'ccc.css' %}">
</head>
<body class="head">
    <h1 class="text_strong">Pricing Table</h1>
   <p class="text">Lorem ipsum dolor sit amet, consectetur adipicing <br>
     elit. Nunc quam urna dignissim nec auctor in,<br>
    mattis vitae leo.</p>
<div class="row">
    <div class="col_left" style="width: 18rem;">
<div class="card-body">
    <h4 class="card-title">BASIC</h4>
      <hr>
    <p class="card-text-1">Lorem ipsum dolor sit amet, consetetur adipiscing elit.</p>
    <b class="card-strong-text">Full Support :</b>
      <p class="card-text">NO</p>
      <b class="card-strong-text">Duration : </b>
      <p class="card-text">30 DAYS</p>
      <b class="card-strong-text">Storage :</b>
      <p class="card-text">10GB</p>
      <h3 class="card-title-1">25$</h3>
    <button type="button" class="btn btn-outline-primary" style="width: 14rem">Buy new</button>
  </div>
</div>
<div class="col_center" style="width: 18rem;">
  <div class="card-body">
    <h4 class="card-title">PRO</h4>
      <hr>
    <p class="card-text-1">Lorem ipsum dolor sit amet, consetetur adipiscing elit.</p>
    <b class="card-strong-text">Full Support :</b>
      <p class="card-text">YES</p>
      <b class="card-strong-text">Duration : </b>
      <p class="card-text">60 DAYS</p>
      <b class="card-strong-text">Storage :</b>
      <p class="card-text">50GB</p>
      <h3 class="card-title-1">50$</h3>
    <button type="button" class="btn btn-outline-primary" style="width: 14rem">Buy new</button>
  </div>
</div>
<div class="col_right" style="width: 18rem">
 <div class="card-body">
    <h4 class="card-title">PREMIUM</h4>
     <hr>
    <p class="card-text-1">Lorem ipsum dolor sit amet, consetetur adipiscing elit.</p>
        <b class="card-strong-text">Full Support :</b>
      <p class="card-text">YES</p>
      <b class="card-strong-text">Duration : </b>
      <p class="card-text">120 DAYS</p>
      <b class="card-strong-text">Storage :</b>
      <p class="card-text">150GB</p>
        <h3 class="card-title-1">150$</h3>
    <button type="button" class="btn btn-outline-primary" style="width: 14rem">Buy new</button>
    </div>
</div>
</div>
</body>
</html>

core/templates/core/sign_in.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ auth_form.as_p }}
        <button>Войти</button>
    </form>
          <form action="action_page.php">
  <div class="container">
    <h1>РЕГАЙСА БРО</h1>
    <p>Ж и Ш пишется через и</p>
    <hr>

    <label for="email"><b>@mail</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>пароль</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label for="psw-repeat"><b>повтори бро а то не понел</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
    <hr>

    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
    <button type="submit" class="registerbtn">нажми суда и регистр готов</button>
  </div>

  <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
  </form>


{% endblock %}

product/templates/about.html
{% extends 'base.html' %}
{% block content %}
<meta charset="UTF-8">
    <h1>О сайте</h1>
    <div>
        Домашка HTML
    </div>
{% endblock %}

product/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href= "{% static 'style.css' %}">
</head>
<body>
    <nav>
        <a href="/">Домой</a>
        <a href="{% url 'categories' %}">Категории</a>
        <a href="/about">О нас</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'feedback' %}">ОС</a>
        {% endif %}
        {% if not request.user.is_authenticated %}
            <a href="{% url 'sign-in' %}">Войти</a>
        {% else %}
            <a href="{% url 'sign-out' %}">Выйти</a>
        {% endif %}
    </nav>
    <div>
        Привет,
        {% if request.user.is_authenticated %}
            {{ request.user.username }}!
        {% else %}
            Друг!
        {% endif %}
    </div>
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

product/templates/product/catigorie.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .wrapper{
        width : 200px;
        height : 200px;
       border: 1px solid #000;
        background : #07F;
        }
        .name {
        color: #FAA;
        }
        .kol-vo {
       color: #FAA
       }

    </style>
</head>
<body>
<h1>Список категорий</h1>
{% for cat in object_list %}
<div><a href="{% url 'category' cat.id %}">{{ cat.name }}</a></div>
<div class="wrapper">
    <p class="name">{{cat.name}}</p>
    <p class="kol-vo">{{cat.description}}</p>
</div>
{% endfor %}
</body>
</html>

product/templates/product/list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Список овощей</h1>
    {% if perms.product.add_vegetables %}
    <div>
        <a href={% url 'vegetable_add' %} class="btn btn-success">Добавить</a>
    </div>
    {% endif %}
    <br/>
    <div class="row">
    {% for vegetable in object_list %}
        <div class="col-4 vegs">
            <div>
                <h2><a href="/vegetables/{{ vegetable.id }}">{{ vegetable.name }}</a></h2>
                <h3>{{ vegetable.price }} сом</h3>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

product/templates/product/vegetable_form.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ vegetable_form.as_p }}
        <button>Сохранить</button>
    </form>

{% endblock %}

product/templates/product/vegetable_info.html
{% extends 'base.html' %}
{% block content %}
    <h2 class="name">{{ vegetables.name }}</h2>
    <div>
        {{ vegetables.description }}
        <hr>
        Калорийность: {{ vegetables.calories }}
    </div>
    <h3>
        {{ vegetables.price }} сом
    </h3>
    <a class="btn btn-warning" href="{% url 'vegetable-update' vegetables.id %}">Изменить</a>
    <form action="{% url 'vegetable-delete' vegetables.id %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Удалить</button>
    </form>
{% endblock %}